parameters:
  - name: serviceDisplayName
    type: string
    default: 'YourServiceDisplayName'

jobs:
- job: Build
  pool:
    name: Pipeline
    agent: DGA1AXST3IB
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $serviceDisplayName = 'Russo'

        # Find the service by display name
        $service = Get-Service | Where-Object { $_.DisplayName -eq $serviceDisplayName }

        if ($service) {
          # Restart the service
          Restart-Service -Name $service.Name -Force
          Write-Host "Service with Display Name '$serviceDisplayName' has been restarted."
        } else {
          Write-Host "Service with Display Name '$serviceDisplayName' not found."
    displayName: 'Restart Service by Display Name'
