trigger:
  branches:
    include:
      - main  # This pipeline triggers when changes are made to the main branch

pool:
  name: 'Default'  # Make sure to select the correct self-hosted agent pool

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Replace with your service name
        $serviceName = 'YourServiceName'

        # Check if the service exists
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service) {
          # Restart the service
          Restart-Service -Name $serviceName -Force
          Write-Host "Service '$serviceName' has been restarted."
        } else {
          Write-Host "Service '$serviceName' not found."
        }
    displayName: 'Restart Service'
